/* Do not edit this file. It is produced from the corresponding .m4 source */
/*
 *  Copyright (C) 2003, Northwestern University and Argonne National Laboratory
 *  See COPYRIGHT notice in top-level directory.
 */
/* $Id: bput.m4 2320 2016-02-24 13:18:32Z wkliao $ */

#if HAVE_CONFIG_H
# include "ncconfig.h"
#endif

#include <stdio.h>
#include <unistd.h>
#ifdef HAVE_STDLIB_H
#include <stdlib.h>
#endif
#include <assert.h>

#include <mpi.h>

#include "nc.h"
#include "ncx.h"
#include "ncmpidtype.h"
#include "macro.h"


/*----< ncmpi_bput_var() >----------------------------------------------------*/
int
ncmpi_bput_var(int           ncid,
               int           varid,
               const void   *buf,
               MPI_Offset    bufcount,
               MPI_Datatype  buftype,
               int          *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, bufcount, API_VAR,
                                 0, 1, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)buf, bufcount, buftype, reqid,
                                 WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}



/*----< ncmpi_bput_var_text() >-------------------------------------------------*/
int
ncmpi_bput_var_text(int       ncid,
                  int       varid,
                  const char *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_CHAR, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_schar() >-------------------------------------------------*/
int
ncmpi_bput_var_schar(int       ncid,
                  int       varid,
                  const schar *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_SIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_uchar() >-------------------------------------------------*/
int
ncmpi_bput_var_uchar(int       ncid,
                  int       varid,
                  const uchar *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_UNSIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_short() >-------------------------------------------------*/
int
ncmpi_bput_var_short(int       ncid,
                  int       varid,
                  const short *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_SHORT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_ushort() >-------------------------------------------------*/
int
ncmpi_bput_var_ushort(int       ncid,
                  int       varid,
                  const ushort *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_UNSIGNED_SHORT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_int() >-------------------------------------------------*/
int
ncmpi_bput_var_int(int       ncid,
                  int       varid,
                  const int *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_INT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_uint() >-------------------------------------------------*/
int
ncmpi_bput_var_uint(int       ncid,
                  int       varid,
                  const uint *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_UNSIGNED, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_long() >-------------------------------------------------*/
int
ncmpi_bput_var_long(int       ncid,
                  int       varid,
                  const long *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_LONG, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_float() >-------------------------------------------------*/
int
ncmpi_bput_var_float(int       ncid,
                  int       varid,
                  const float *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_FLOAT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_double() >-------------------------------------------------*/
int
ncmpi_bput_var_double(int       ncid,
                  int       varid,
                  const double *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_DOUBLE, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_longlong() >-------------------------------------------------*/
int
ncmpi_bput_var_longlong(int       ncid,
                  int       varid,
                  const long long *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_LONG_LONG_INT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}

/*----< ncmpi_bput_var_ulonglong() >-------------------------------------------------*/
int
ncmpi_bput_var_ulonglong(int       ncid,
                  int       varid,
                  const unsigned long long *op,
                  int      *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset  *start, *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, NULL, NULL, 0, API_VAR,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_FULL_DIMENSIONS(start, count)

    /* bput_var is a special case of bput_varm */
    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_UNSIGNED_LONG_LONG, reqid, WRITE_REQ, 1, 0);
    NCI_Free(start);
    return status;
}



/*----< ncmpi_bput_var1() >---------------------------------------------------*/
int
ncmpi_bput_var1(int               ncid,
                int               varid,
                const MPI_Offset *start,
                const void       *buf,
                MPI_Offset        bufcount,
                MPI_Datatype      buftype,
                int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, bufcount, API_VAR1,
                                 0, 1, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)buf, bufcount, buftype, reqid,
                                 WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}


/*----< ncmpi_bput_var1_text() >------------------------------------------------*/
int
ncmpi_bput_var1_text(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const char         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_CHAR, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_schar() >------------------------------------------------*/
int
ncmpi_bput_var1_schar(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const schar         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_SIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_uchar() >------------------------------------------------*/
int
ncmpi_bput_var1_uchar(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const uchar         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_UNSIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_short() >------------------------------------------------*/
int
ncmpi_bput_var1_short(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const short         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_SHORT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_ushort() >------------------------------------------------*/
int
ncmpi_bput_var1_ushort(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const ushort         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_UNSIGNED_SHORT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_int() >------------------------------------------------*/
int
ncmpi_bput_var1_int(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const int         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_INT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_uint() >------------------------------------------------*/
int
ncmpi_bput_var1_uint(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const uint         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_UNSIGNED, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_long() >------------------------------------------------*/
int
ncmpi_bput_var1_long(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_LONG, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_float() >------------------------------------------------*/
int
ncmpi_bput_var1_float(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const float         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_FLOAT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_double() >------------------------------------------------*/
int
ncmpi_bput_var1_double(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const double         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_DOUBLE, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_longlong() >------------------------------------------------*/
int
ncmpi_bput_var1_longlong(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const long long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_LONG_LONG_INT, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}

/*----< ncmpi_bput_var1_ulonglong() >------------------------------------------------*/
int
ncmpi_bput_var1_ulonglong(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const unsigned long long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;
    MPI_Offset *count;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, NULL, 0, API_VAR1,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    GET_ONE_COUNT(count)

    status = ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                                 (void*)op, -1, MPI_UNSIGNED_LONG_LONG, reqid, WRITE_REQ, 1, 0);
    NCI_Free(count);
    return status;
}



/*----< ncmpi_bput_vara() >---------------------------------------------------*/
int
ncmpi_bput_vara(int               ncid,
                int               varid,
                const MPI_Offset *start,
                const MPI_Offset *count,
                const void       *buf,
                MPI_Offset        bufcount,
                MPI_Datatype      buftype,
                int              *reqid)
{
    int     status;
    NC     *ncp;
    NC_var *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, bufcount, API_VARA,
                                 0, 1, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)buf, bufcount, buftype, reqid,
                               WRITE_REQ, 1, 0);
}


/*----< ncmpi_bput_vara_text() >------------------------------------------------*/
int
ncmpi_bput_vara_text(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const char         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_CHAR, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_schar() >------------------------------------------------*/
int
ncmpi_bput_vara_schar(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const schar         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_SIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_uchar() >------------------------------------------------*/
int
ncmpi_bput_vara_uchar(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const uchar         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_UNSIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_short() >------------------------------------------------*/
int
ncmpi_bput_vara_short(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const short         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_SHORT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_ushort() >------------------------------------------------*/
int
ncmpi_bput_vara_ushort(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const ushort         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_UNSIGNED_SHORT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_int() >------------------------------------------------*/
int
ncmpi_bput_vara_int(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const int         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_INT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_uint() >------------------------------------------------*/
int
ncmpi_bput_vara_uint(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const uint         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_UNSIGNED, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_long() >------------------------------------------------*/
int
ncmpi_bput_vara_long(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_LONG, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_float() >------------------------------------------------*/
int
ncmpi_bput_vara_float(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const float         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_FLOAT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_double() >------------------------------------------------*/
int
ncmpi_bput_vara_double(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const double         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_DOUBLE, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_longlong() >------------------------------------------------*/
int
ncmpi_bput_vara_longlong(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const long long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_LONG_LONG_INT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vara_ulonglong() >------------------------------------------------*/
int
ncmpi_bput_vara_ulonglong(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const unsigned long long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARA,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, NULL, NULL,
                               (void*)op, -1, MPI_UNSIGNED_LONG_LONG, reqid, WRITE_REQ, 1, 0);
}



/*----< ncmpi_bput_vars() >---------------------------------------------------*/
int
ncmpi_bput_vars(int               ncid,
                int               varid,
                const MPI_Offset  start[],
                const MPI_Offset  count[],
                const MPI_Offset  stride[],
                const void       *buf,
                MPI_Offset        bufcount,
                MPI_Datatype      buftype,
                int              *reqid)
{
    int     status;
    NC     *ncp;
    NC_var *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, bufcount, API_VARS,
                                 0, 1, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)buf, bufcount, buftype, reqid,
                               WRITE_REQ, 1, 0);
}


/*----< ncmpi_bput_vars_text() >------------------------------------------------*/
int
ncmpi_bput_vars_text(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const char         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_CHAR, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_schar() >------------------------------------------------*/
int
ncmpi_bput_vars_schar(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const schar         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_SIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_uchar() >------------------------------------------------*/
int
ncmpi_bput_vars_uchar(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const uchar         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_UNSIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_short() >------------------------------------------------*/
int
ncmpi_bput_vars_short(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const short         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_SHORT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_ushort() >------------------------------------------------*/
int
ncmpi_bput_vars_ushort(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const ushort         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_UNSIGNED_SHORT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_int() >------------------------------------------------*/
int
ncmpi_bput_vars_int(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const int         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_INT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_uint() >------------------------------------------------*/
int
ncmpi_bput_vars_uint(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const uint         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_UNSIGNED, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_long() >------------------------------------------------*/
int
ncmpi_bput_vars_long(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_LONG, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_float() >------------------------------------------------*/
int
ncmpi_bput_vars_float(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const float         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_FLOAT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_double() >------------------------------------------------*/
int
ncmpi_bput_vars_double(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const double         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_DOUBLE, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_longlong() >------------------------------------------------*/
int
ncmpi_bput_vars_longlong(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const long long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_LONG_LONG_INT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_vars_ulonglong() >------------------------------------------------*/
int
ncmpi_bput_vars_ulonglong(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const unsigned long long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARS,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, NULL,
                               (void*)op, -1, MPI_UNSIGNED_LONG_LONG, reqid, WRITE_REQ, 1, 0);
}


/*----< ncmpi_bput_varm() >---------------------------------------------------*/
int
ncmpi_bput_varm(int               ncid,
                int               varid,
                const MPI_Offset  start[],
                const MPI_Offset  count[],
                const MPI_Offset  stride[],
                const MPI_Offset  imap[],
                const void       *buf,
                MPI_Offset        bufcount,
                MPI_Datatype      buftype,
                int              *reqid)
{
    int     status;
    NC     *ncp;
    NC_var *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, bufcount, API_VARM,
                                 0, 1, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)buf, bufcount, buftype, reqid,
                               WRITE_REQ, 1, 0);
}


/*----< ncmpi_bput_varm_text() >------------------------------------------------*/
int
ncmpi_bput_varm_text(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const char         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_CHAR, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_schar() >------------------------------------------------*/
int
ncmpi_bput_varm_schar(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const schar         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_SIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_uchar() >------------------------------------------------*/
int
ncmpi_bput_varm_uchar(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const uchar         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_UNSIGNED_CHAR, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_short() >------------------------------------------------*/
int
ncmpi_bput_varm_short(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const short         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_SHORT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_ushort() >------------------------------------------------*/
int
ncmpi_bput_varm_ushort(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const ushort         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_UNSIGNED_SHORT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_int() >------------------------------------------------*/
int
ncmpi_bput_varm_int(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const int         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_INT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_uint() >------------------------------------------------*/
int
ncmpi_bput_varm_uint(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const uint         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_UNSIGNED, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_long() >------------------------------------------------*/
int
ncmpi_bput_varm_long(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_LONG, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_float() >------------------------------------------------*/
int
ncmpi_bput_varm_float(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const float         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_FLOAT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_double() >------------------------------------------------*/
int
ncmpi_bput_varm_double(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const double         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_DOUBLE, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_longlong() >------------------------------------------------*/
int
ncmpi_bput_varm_longlong(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const long long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_LONG_LONG_INT, reqid, WRITE_REQ, 1, 0);
}

/*----< ncmpi_bput_varm_ulonglong() >------------------------------------------------*/
int
ncmpi_bput_varm_ulonglong(int               ncid,
                   int               varid,
                   const MPI_Offset  start[],
                   const MPI_Offset  count[],
                   const MPI_Offset  stride[],
                   const MPI_Offset  imap[],
                   const unsigned long long         *op,
                   int              *reqid)
{
    int         status;
    NC         *ncp;
    NC_var     *varp=NULL;

    if (reqid != NULL) *reqid = NC_REQ_NULL;
    status = ncmpii_sanity_check(ncid, varid, start, count, 0, API_VARM,
                                 0, 0, WRITE_REQ, NONBLOCKING_IO, &ncp, &varp);
    if (status != NC_NOERR) return status;

    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    return ncmpii_igetput_varm(ncp, varp, start, count, stride, imap,
                               (void*)op, -1, MPI_UNSIGNED_LONG_LONG, reqid, WRITE_REQ, 1, 0);
}



/*----< ncmpi_buffer_attach() >-----------------------------------------------*/
int
ncmpi_buffer_attach(int        ncid,
                    MPI_Offset bufsize)
{
    int status;
    NC *ncp;

    if (bufsize <= 0) DEBUG_RETURN_ERROR(NC_ENULLBUF)

    status = ncmpii_NC_check_id(ncid, &ncp);
    if (status != NC_NOERR) return status;

    /* check if the buffer has been previously attached
     * note that in nc.c, the NC object is allocated with calloc, so
     * abuf should be initialized to NULL then
     */
    if (ncp->abuf != NULL) DEBUG_RETURN_ERROR(NC_EPREVATTACHBUF)

    ncp->abuf = (NC_buf*) NCI_Malloc(sizeof(NC_buf));

    ncp->abuf->size_allocated = bufsize;
    ncp->abuf->size_used = 0;
    ncp->abuf->table_size = NC_ABUF_DEFAULT_TABLE_SIZE;
    ncp->abuf->occupy_table = (NC_buf_status*)
               NCI_Calloc(NC_ABUF_DEFAULT_TABLE_SIZE, sizeof(NC_buf_status));
    ncp->abuf->tail = 0;
    ncp->abuf->buf = NCI_Malloc((size_t)bufsize);
    return NC_NOERR;
}

/*----< ncmpi_buffer_detach() >-----------------------------------------------*/
int
ncmpi_buffer_detach(int ncid)
{
    int     status;
    NC     *ncp;
    NC_req *cur_req;

    status = ncmpii_NC_check_id(ncid, &ncp);
    if (status != NC_NOERR) return status;

    /* check if the buffer has been previously attached */
    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    /* this API assumes users are responsible for no pending bput */
    cur_req = ncp->head;
    while (cur_req != NULL) { /* check if there is a pending bput */
        if (cur_req->abuf_index >= 0)
            DEBUG_RETURN_ERROR(NC_EPENDINGBPUT)
            /* return now, so users can call wait and try detach again */
        cur_req = cur_req->next;
    }

    NCI_Free(ncp->abuf->buf);
    NCI_Free(ncp->abuf->occupy_table);
    NCI_Free(ncp->abuf);
    ncp->abuf = NULL;

    return NC_NOERR;
}

#ifdef THIS_SEEMS_OVER_DONE_IT
/*----< ncmpi_buffer_detach() >-----------------------------------------------*/
/* mimic MPI_Buffer_detach()
 * Note from MPI: Even though the 'bufferptr' argument is declared as
 * 'void *', it is really the address of a void pointer.
 */
int
ncmpi_buffer_detach(int         ncid,
                    void       *bufptr,
                    MPI_Offset *bufsize)
{
    int     status;
    NC     *ncp;
    NC_req *cur_req;

    status = ncmpii_NC_check_id(ncid, &ncp);
    if (status != NC_NOERR) return status;

    /* check if the buffer has been previously attached */
    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    /* check MPICH2 src/mpi/pt2pt/bsendutil.c for why the bufptr is void* */
    *(void **)bufptr = ncp->abuf->buf;
    *bufsize         = ncp->abuf->size_allocated;

    /* this API assumes users are responsible for no pending bput when called */
    cur_req = ncp->head;
    while (cur_req != NULL) { /* check if there is a pending bput */
        if (cur_req->abuf_index >= 0)
            DEBUG_RETURN_ERROR(NC_EPENDINGBPUT)
        cur_req = cur_req->next;
    }

    NCI_Free(ncp->abuf->occupy_table);
    NCI_Free(ncp->abuf);
    ncp->abuf = NULL;

    return NC_NOERR;
}
#endif


/*----< ncmpi_inq_buffer_usage() >--------------------------------------------*/
int
ncmpi_inq_buffer_usage(int         ncid,
                       MPI_Offset *usage) /* OUT: in bytes */
{
    int  status;
    NC  *ncp;

    status = ncmpii_NC_check_id(ncid, &ncp);
    if (status != NC_NOERR) return status;

    /* check if the buffer has been previously attached */
    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    /* return the current usage in bytes */
    *usage = ncp->abuf->size_used;

    return NC_NOERR;
}

/*----< ncmpi_inq_buffer_size() >---------------------------------------------*/
int
ncmpi_inq_buffer_size(int         ncid,
                      MPI_Offset *buf_size) /* OUT: in bytes */
{
    int  status;
    NC  *ncp;

    status = ncmpii_NC_check_id(ncid, &ncp);
    if (status != NC_NOERR) return status;

    /* check if the buffer has been previously attached */
    if (ncp->abuf == NULL) DEBUG_RETURN_ERROR(NC_ENULLABUF)

    /* return the current usage in bytes */
    *buf_size = ncp->abuf->size_allocated;

    return NC_NOERR;
}

