# CMake generated Testfile for 
# Source directory: /Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/hl/examples
# Build directory: /Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/hl/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(HL_ex-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "ex_lite1.h5" "ex_lite2.h5" "ex_lite3.h5" "packet_table_FLexample.h5" "ex_image1.h5" "ex_image2.h5" "ex_table_01.h5" "ex_table_02.h5" "ex_table_03.h5" "ex_table_04.h5" "ex_table_05.h5" "ex_table_06.h5" "ex_table_07.h5" "ex_table_08.h5" "ex_table_09.h5" "ex_table_10.h5" "ex_table_11.h5" "ex_table_12.h5" "ex_ds1.h5")
add_test(HL_ex_ex_lite1 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_lite1")
set_tests_properties(HL_ex_ex_lite1 PROPERTIES  DEPENDS "HL_ex-clear-objects")
add_test(HL_ex_ex_lite2 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_lite2")
set_tests_properties(HL_ex_ex_lite2 PROPERTIES  DEPENDS "HL_ex_ex_lite1")
add_test(HL_ex_ex_lite3 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_lite3")
set_tests_properties(HL_ex_ex_lite3 PROPERTIES  DEPENDS "HL_ex_ex_lite2")
add_test(HL_ex_ptExampleFL "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ptExampleFL")
set_tests_properties(HL_ex_ptExampleFL PROPERTIES  DEPENDS "HL_ex_ex_lite3")
add_test(HL_ex_ex_image1 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_image1")
set_tests_properties(HL_ex_ex_image1 PROPERTIES  DEPENDS "HL_ex_ptExampleFL")
add_test(HL_ex_ex_image2 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_image2")
set_tests_properties(HL_ex_ex_image2 PROPERTIES  DEPENDS "HL_ex_ex_image1")
add_test(HL_ex_ex_table_01 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_01")
set_tests_properties(HL_ex_ex_table_01 PROPERTIES  DEPENDS "HL_ex_ex_image2")
add_test(HL_ex_ex_table_02 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_02")
set_tests_properties(HL_ex_ex_table_02 PROPERTIES  DEPENDS "HL_ex_ex_table_01")
add_test(HL_ex_ex_table_03 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_03")
set_tests_properties(HL_ex_ex_table_03 PROPERTIES  DEPENDS "HL_ex_ex_table_02")
add_test(HL_ex_ex_table_04 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_04")
set_tests_properties(HL_ex_ex_table_04 PROPERTIES  DEPENDS "HL_ex_ex_table_03")
add_test(HL_ex_ex_table_05 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_05")
set_tests_properties(HL_ex_ex_table_05 PROPERTIES  DEPENDS "HL_ex_ex_table_04")
add_test(HL_ex_ex_table_06 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_06")
set_tests_properties(HL_ex_ex_table_06 PROPERTIES  DEPENDS "HL_ex_ex_table_05")
add_test(HL_ex_ex_table_07 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_07")
set_tests_properties(HL_ex_ex_table_07 PROPERTIES  DEPENDS "HL_ex_ex_table_06")
add_test(HL_ex_ex_table_08 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_08")
set_tests_properties(HL_ex_ex_table_08 PROPERTIES  DEPENDS "HL_ex_ex_table_07")
add_test(HL_ex_ex_table_09 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_09")
set_tests_properties(HL_ex_ex_table_09 PROPERTIES  DEPENDS "HL_ex_ex_table_08")
add_test(HL_ex_ex_table_10 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_10")
set_tests_properties(HL_ex_ex_table_10 PROPERTIES  DEPENDS "HL_ex_ex_table_09")
add_test(HL_ex_ex_table_11 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_11")
set_tests_properties(HL_ex_ex_table_11 PROPERTIES  DEPENDS "HL_ex_ex_table_10")
add_test(HL_ex_ex_table_12 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_table_12")
set_tests_properties(HL_ex_ex_table_12 PROPERTIES  DEPENDS "HL_ex_ex_table_11")
add_test(HL_ex_ex_ds1 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/hl_ex_ex_ds1")
set_tests_properties(HL_ex_ex_ds1 PROPERTIES  DEPENDS "HL_ex_ex_table_12")
