# CMake generated Testfile for 
# Source directory: /Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/examples
# Build directory: /Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(EXAMPLES-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "Attributes.h5" "btrees_file.h5" "cmprss.h5" "default_file.h5" "dset.h5" "extend.h5" "extlink_prefix_source.h5" "extlink_source.h5" "extlink_target.h5" "group.h5" "groups.h5" "hard_link.h5" "mount1.h5" "mount2.h5" "one_index_file.h5" "only_dspaces_and_attrs_file.h5" "only_huge_mesgs_file.h5" "REF_REG.h5" "refere.h5" "SDS.h5" "SDScompound.h5" "SDSextendible.h5" "Select.h5" "separate_indexes_file.h5" "small_lists_file.h5" "soft_link.h5" "subset.h5" "unix2win.h5" "blue/prefix_target.h5" "red/prefix_target.h5" "u2w/u2w_target.h5")
add_test(EXAMPLES-h5_crtdat "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_crtdat")
set_tests_properties(EXAMPLES-h5_crtdat PROPERTIES  DEPENDS "EXAMPLES-clear-objects")
add_test(EXAMPLES-h5_rdwt "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_rdwt")
set_tests_properties(EXAMPLES-h5_rdwt PROPERTIES  DEPENDS "EXAMPLES-h5_crtdat")
add_test(EXAMPLES-h5_crtatt "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_crtatt")
set_tests_properties(EXAMPLES-h5_crtatt PROPERTIES  DEPENDS "EXAMPLES-h5_rdwt")
add_test(EXAMPLES-h5_crtgrp "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_crtgrp")
set_tests_properties(EXAMPLES-h5_crtgrp PROPERTIES  DEPENDS "EXAMPLES-h5_crtatt")
add_test(EXAMPLES-h5_crtgrpar "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_crtgrpar")
set_tests_properties(EXAMPLES-h5_crtgrpar PROPERTIES  DEPENDS "EXAMPLES-h5_crtgrp")
add_test(EXAMPLES-h5_crtgrpd "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_crtgrpd")
set_tests_properties(EXAMPLES-h5_crtgrpd PROPERTIES  DEPENDS "EXAMPLES-h5_crtgrpar")
add_test(EXAMPLES-h5_cmprss "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_cmprss")
set_tests_properties(EXAMPLES-h5_cmprss PROPERTIES  DEPENDS "EXAMPLES-h5_crtgrpd")
add_test(EXAMPLES-h5_extend "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_extend")
set_tests_properties(EXAMPLES-h5_extend PROPERTIES  DEPENDS "EXAMPLES-h5_cmprss")
add_test(EXAMPLES-h5_subset "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_subset")
set_tests_properties(EXAMPLES-h5_subset PROPERTIES  DEPENDS "EXAMPLES-h5_extend")
add_test(EXAMPLES-h5_write "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_write")
set_tests_properties(EXAMPLES-h5_write PROPERTIES  DEPENDS "EXAMPLES-h5_subset")
add_test(EXAMPLES-h5_read "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_read")
set_tests_properties(EXAMPLES-h5_read PROPERTIES  DEPENDS "EXAMPLES-h5_write")
add_test(EXAMPLES-h5_extend_write "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_extend_write")
set_tests_properties(EXAMPLES-h5_extend_write PROPERTIES  DEPENDS "EXAMPLES-h5_read")
add_test(EXAMPLES-h5_chunk_read "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_chunk_read")
set_tests_properties(EXAMPLES-h5_chunk_read PROPERTIES  DEPENDS "EXAMPLES-h5_extend_write")
add_test(EXAMPLES-h5_compound "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_compound")
set_tests_properties(EXAMPLES-h5_compound PROPERTIES  DEPENDS "EXAMPLES-h5_chunk_read")
add_test(EXAMPLES-h5_group "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_group")
set_tests_properties(EXAMPLES-h5_group PROPERTIES  DEPENDS "EXAMPLES-h5_compound")
add_test(EXAMPLES-h5_select "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_select")
set_tests_properties(EXAMPLES-h5_select PROPERTIES  DEPENDS "EXAMPLES-h5_group")
add_test(EXAMPLES-h5_attribute "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_attribute")
set_tests_properties(EXAMPLES-h5_attribute PROPERTIES  DEPENDS "EXAMPLES-h5_select")
add_test(EXAMPLES-h5_mount "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_mount")
set_tests_properties(EXAMPLES-h5_mount PROPERTIES  DEPENDS "EXAMPLES-h5_attribute")
add_test(EXAMPLES-h5_reference "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_reference")
set_tests_properties(EXAMPLES-h5_reference PROPERTIES  DEPENDS "EXAMPLES-h5_mount")
add_test(EXAMPLES-h5_drivers "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_drivers")
set_tests_properties(EXAMPLES-h5_drivers PROPERTIES  DEPENDS "EXAMPLES-h5_reference")
add_test(EXAMPLES-h5_ref2reg "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_ref2reg")
set_tests_properties(EXAMPLES-h5_ref2reg PROPERTIES  DEPENDS "EXAMPLES-h5_drivers")
add_test(EXAMPLES-h5_extlink "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_extlink")
set_tests_properties(EXAMPLES-h5_extlink PROPERTIES  DEPENDS "EXAMPLES-h5_ref2reg")
add_test(EXAMPLES-h5_elink_unix2win "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_elink_unix2win")
set_tests_properties(EXAMPLES-h5_elink_unix2win PROPERTIES  DEPENDS "EXAMPLES-h5_extlink")
add_test(EXAMPLES-h5_shared_mesg "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5_shared_mesg")
set_tests_properties(EXAMPLES-h5_shared_mesg PROPERTIES  DEPENDS "EXAMPLES-h5_elink_unix2win")
add_test(EXAMPLES-ph5example "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/ph5example")
set_tests_properties(EXAMPLES-ph5example PROPERTIES  DEPENDS "EXAMPLES-h5_shared_mesg")
