# Generated by CMake 3.6.0

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget hdf5-static hdf5_tools-static hdf5_hl-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target hdf5-static
add_library(hdf5-static STATIC IMPORTED)

set_target_properties(hdf5-static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/src;/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/src"
  INTERFACE_LINK_LIBRARIES "m;dl;/Users/tjcorona/Development/Software/Albany/install/lib/libmpi.dylib;/Users/tjcorona/Development/Software/Albany/install/lib/libpmpi.dylib;/Users/tjcorona/Development/Software/Albany/install/lib/libz.dylib;dl;/Users/tjcorona/Development/Software/Albany/install/lib/libmpi.dylib;/Users/tjcorona/Development/Software/Albany/install/lib/libpmpi.dylib"
)

# Create imported target hdf5_tools-static
add_library(hdf5_tools-static STATIC IMPORTED)

set_target_properties(hdf5_tools-static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/tools/lib;/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/tools/lib"
  INTERFACE_LINK_LIBRARIES "hdf5-static"
)

# Create imported target hdf5_hl-static
add_library(hdf5_hl-static STATIC IMPORTED)

set_target_properties(hdf5_hl-static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/hl/src;/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/hl/src"
  INTERFACE_LINK_LIBRARIES "hdf5-static"
)

# Import target "hdf5-static" for configuration ""
set_property(TARGET hdf5-static APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(hdf5-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/libhdf5-static.a"
  )

# Import target "hdf5_tools-static" for configuration ""
set_property(TARGET hdf5_tools-static APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(hdf5_tools-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/libhdf5_tools-static.a"
  )

# Import target "hdf5_hl-static" for configuration ""
set_property(TARGET hdf5_hl-static APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(hdf5_hl-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/libhdf5_hl-static.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
