/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2003 by Argonne National Laboratory and Northwestern University.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by ./buildiface -infile=../lib/pnetcdf.h -deffile=./defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_fill_var_rec_ NFMPI_FILL_VAR_REC
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_fill_var_rec_ nfmpi_fill_var_rec__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_fill_var_rec_ nfmpi_fill_var_rec
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API int FORT_CALL nfmpi_fill_var_rec_ ( int *v1, int *v2, MPI_Offset *v3 ){
    int ierr;
    int l2 = *v2 - 1;
    MPI_Offset l3 = *v3 - 1;
    ierr = ncmpi_fill_var_rec( *v1, l2, l3 );
    return ierr;
}
