/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2003 by Argonne National Laboratory and Northwestern University.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by ./buildiface -infile=../lib/pnetcdf.h -deffile=./defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_get_att_ NFMPI_GET_ATT
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_get_att_ nfmpi_get_att__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_get_att_ nfmpi_get_att
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API int FORT_CALL nfmpi_get_att_ ( int *v1, int *v2, char *v3 FORT_MIXED_LEN(d3), void *v4 FORT_END_LEN(d3) ){
    int ierr;
    ierr = ncmpi_get_att( *v1, *v2, v3, v4 );
    return ierr;
}
