/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2003 by Argonne National Laboratory and Northwestern University.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by ./buildiface -infile=../lib/pnetcdf.h -deffile=./defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_inq_var_ NFMPI_INQ_VAR
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_inq_var_ nfmpi_inq_var__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_inq_var_ nfmpi_inq_var
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API int FORT_CALL nfmpi_inq_var_ ( int *v1, int *v2, char *v3 FORT_MIXED_LEN(d3), int *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7 FORT_END_LEN(d3) ){
    int ierr;
    int l2 = *v2 - 1;
    char *p3;
    int *l6=NULL;
    p3 = (char*) calloc((size_t)d3 + 1, 1);

    int ndims;
    ierr = ncmpi_inq_varndims(*v1, l2, &ndims); /* get number of dimensions */
    if (ierr != NC_NOERR) return ierr;

    if (ndims > 0) {
        l6 = (int*) malloc((size_t)ndims * sizeof(int));
    }
    ierr = ncmpi_inq_var( *v1, l2, p3, (nc_type *)(v4), v5, l6, v7 );

    {
        char *p = v3, *pc=p3;
        while (*pc) {*p++ = *pc++;}
        while ((p-v3) < d3) { *p++ = ' '; }
    }
    free(p3);

    if (ndims > 0) {
        int li;
        for (li=0; li<ndims; li++) /* convert C order to Fortran order */
            v6[li] = l6[ndims-1-li] + 1; /* convert from 0-based to 1-based */
        free(l6);
    }
    return ierr;
}
