/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2003 by Argonne National Laboratory and Northwestern University.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by ./buildiface -infile=../lib/pnetcdf.h -deffile=./defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_inq_vardimid_ NFMPI_INQ_VARDIMID
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_inq_vardimid_ nfmpi_inq_vardimid__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_inq_vardimid_ nfmpi_inq_vardimid
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API int FORT_CALL nfmpi_inq_vardimid_ ( int *v1, int *v2, MPI_Fint *v3 ){
    int ierr;
    int l2 = *v2 - 1;
    int *l3=NULL;

    int ndims;
    ierr = ncmpi_inq_varndims(*v1, l2, &ndims); /* get number of dimensions */
    if (ierr != NC_NOERR) return ierr;

    if (ndims > 0) {
        l3 = (int*) malloc((size_t)ndims * sizeof(int));
    }
    ierr = ncmpi_inq_vardimid( *v1, l2, l3 );

    if (ndims > 0) {
        int li;
        for (li=0; li<ndims; li++) /* convert C order to Fortran order */
            v3[li] = l3[ndims-1-li] + 1; /* convert from 0-based to 1-based */
        free(l3);
    }
    return ierr;
}
