# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "documentation;headers;libraries;utilities")
SET(CPACK_COMPONENT_DEPENDENCIES_DESCRIPTION "Dependencies for this build of NetCDF-C")
SET(CPACK_COMPONENT_DOCUMENTATION_DESCRIPTION "The NetCDF-C user documentation.")
SET(CPACK_COMPONENT_HEADERS_DESCRIPTION "Header files for use with NetCDF-C")
SET(CPACK_COMPONENT_LIBRARIES_DESCRIPTION "The NetCDF-C Libraries")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_COMPONENT_UTILITIES_DESCRIPTION "The NetCDF-C Utilities")
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_IGNORE_FILES ";/expecttds3/;/nocacheremote3/;/nocacheremote4/;/special3/;/Users/tjcorona/Development/Software/Albany/Dependencies/netcdf-4.4.0/build/*;/myhtml/*;/.svn/;my.*\\.sh;/.deps/;/.libs;/html/;.*\\.jar;.*\\.jdl;.*\\.sed;.*\\.proto;.*\\.texi;.*\\.example;Make0;/obsolete/;/unknown/;.*~")
SET(CPACK_INSTALLED_DIRECTORIES "/Users/tjcorona/Development/Software/Albany/Dependencies/netcdf-4.4.0;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/Users/tjcorona/Development/Software/Albany/install")
SET(CPACK_MODULE_PATH "/Users/tjcorona/Development/Software/Albany/Dependencies/netcdf-4.4.0/cmake/modules/")
SET(CPACK_NSIS_DISPLAY_NAME "netCDF 4.4.0")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "netCDF 4.4.0")
SET(CPACK_OUTPUT_CONFIG_FILE "/Users/tjcorona/Development/Software/Albany/Dependencies/netcdf-4.4.0/build/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "NetCDF Support <support-netcdf@unidata.ucar.edu>")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/Cellar/cmake/3.6.2/share/cmake/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "netCDF built using CMake")
SET(CPACK_PACKAGE_FILE_NAME "netCDF-4.4.0-Source")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "netCDF 4.4.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "netCDF 4.4.0")
SET(CPACK_PACKAGE_NAME "netCDF")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Unidata")
SET(CPACK_PACKAGE_VERSION "4.4.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "/Users/tjcorona/Development/Software/Albany/Dependencies/netcdf-4.4.0/build/COPYRIGHT.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/local/Cellar/cmake/3.6.2/share/cmake/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/local/Cellar/cmake/3.6.2/share/cmake/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_IGNORE_FILES ";/expecttds3/;/nocacheremote3/;/nocacheremote4/;/special3/;/Users/tjcorona/Development/Software/Albany/Dependencies/netcdf-4.4.0/build/*;/myhtml/*;/.svn/;my.*\\.sh;/.deps/;/.libs;/html/;.*\\.jar;.*\\.jdl;.*\\.sed;.*\\.proto;.*\\.texi;.*\\.example;Make0;/obsolete/;/unknown/;.*~")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/tjcorona/Development/Software/Albany/Dependencies/netcdf-4.4.0;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/tjcorona/Development/Software/Albany/Dependencies/netcdf-4.4.0/build/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "netCDF-4.4.0-Source")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Darwin")
SET(CPACK_TOPLEVEL_TAG "Darwin-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/tjcorona/Development/Software/Albany/Dependencies/netcdf-4.4.0/build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
