# CMake generated Testfile for 
# Source directory: /Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/tools/h5copy
# Build directory: /Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/tools/h5copy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(H5COPY-simple-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/simple.out.h5")
add_test(H5COPY-simple "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/simple.out.h5" "-v" "-s" "simple" "-d" "simple")
set_tests_properties(H5COPY-simple PROPERTIES  DEPENDS "H5COPY-simple-clear-objects")
add_test(H5COPY-simple-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/simple.out.h5" "simple" "simple")
set_tests_properties(H5COPY-simple-DIFF PROPERTIES  DEPENDS "H5COPY-simple")
add_test(H5COPY-chunk-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/chunk.out.h5")
add_test(H5COPY-chunk "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/chunk.out.h5" "-v" "-s" "chunk" "-d" "chunk")
set_tests_properties(H5COPY-chunk PROPERTIES  DEPENDS "H5COPY-chunk-clear-objects")
add_test(H5COPY-chunk-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/chunk.out.h5" "chunk" "chunk")
set_tests_properties(H5COPY-chunk-DIFF PROPERTIES  DEPENDS "H5COPY-chunk")
add_test(H5COPY-compact-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/compact.out.h5")
add_test(H5COPY-compact "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/compact.out.h5" "-v" "-s" "compact" "-d" "compact")
set_tests_properties(H5COPY-compact PROPERTIES  DEPENDS "H5COPY-compact-clear-objects")
add_test(H5COPY-compact-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/compact.out.h5" "compact" "compact")
set_tests_properties(H5COPY-compact-DIFF PROPERTIES  DEPENDS "H5COPY-compact")
add_test(H5COPY-compound-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/compound.out.h5")
add_test(H5COPY-compound "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/compound.out.h5" "-v" "-s" "compound" "-d" "compound")
set_tests_properties(H5COPY-compound PROPERTIES  DEPENDS "H5COPY-compound-clear-objects")
add_test(H5COPY-compound-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/compound.out.h5" "compound" "compound")
set_tests_properties(H5COPY-compound-DIFF PROPERTIES  DEPENDS "H5COPY-compound")
add_test(H5COPY-compressed-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/compressed.out.h5")
add_test(H5COPY-compressed "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/compressed.out.h5" "-v" "-s" "compressed" "-d" "compressed")
set_tests_properties(H5COPY-compressed PROPERTIES  DEPENDS "H5COPY-compressed-clear-objects")
add_test(H5COPY-compressed-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/compressed.out.h5" "compressed" "compressed")
set_tests_properties(H5COPY-compressed-DIFF PROPERTIES  DEPENDS "H5COPY-compressed")
add_test(H5COPY-named_vl-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/named_vl.out.h5")
add_test(H5COPY-named_vl "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/named_vl.out.h5" "-v" "-s" "named_vl" "-d" "named_vl")
set_tests_properties(H5COPY-named_vl PROPERTIES  DEPENDS "H5COPY-named_vl-clear-objects")
add_test(H5COPY-named_vl-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/named_vl.out.h5" "named_vl" "named_vl")
set_tests_properties(H5COPY-named_vl-DIFF PROPERTIES  DEPENDS "H5COPY-named_vl")
add_test(H5COPY-nested_vl-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/nested_vl.out.h5")
add_test(H5COPY-nested_vl "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/nested_vl.out.h5" "-v" "-s" "nested_vl" "-d" "nested_vl")
set_tests_properties(H5COPY-nested_vl PROPERTIES  DEPENDS "H5COPY-nested_vl-clear-objects")
add_test(H5COPY-nested_vl-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/nested_vl.out.h5" "nested_vl" "nested_vl")
set_tests_properties(H5COPY-nested_vl-DIFF PROPERTIES  DEPENDS "H5COPY-nested_vl")
add_test(H5COPY-simple_top-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/simple_top.out.h5")
add_test(H5COPY-simple_top "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/simple_top.out.h5" "-v" "-s" "grp_dsets/simple" "-d" "simple_top")
set_tests_properties(H5COPY-simple_top PROPERTIES  DEPENDS "H5COPY-simple_top-clear-objects")
add_test(H5COPY-simple_top-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/simple_top.out.h5" "grp_dsets/simple" "simple_top")
set_tests_properties(H5COPY-simple_top-DIFF PROPERTIES  DEPENDS "H5COPY-simple_top")
add_test(H5COPY-dsrename-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/dsrename.out.h5")
add_test(H5COPY-dsrename "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/dsrename.out.h5" "-v" "-s" "compound" "-d" "rename")
set_tests_properties(H5COPY-dsrename PROPERTIES  DEPENDS "H5COPY-dsrename-clear-objects")
add_test(H5COPY-dsrename-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/dsrename.out.h5" "compound" "rename")
set_tests_properties(H5COPY-dsrename-DIFF PROPERTIES  DEPENDS "H5COPY-dsrename")
add_test(H5COPY-grp_empty-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/grp_empty.out.h5")
add_test(H5COPY-grp_empty "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/grp_empty.out.h5" "-v" "-s" "grp_empty" "-d" "grp_empty")
set_tests_properties(H5COPY-grp_empty PROPERTIES  DEPENDS "H5COPY-grp_empty-clear-objects")
add_test(H5COPY-grp_empty-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/grp_empty.out.h5" "grp_empty" "grp_empty")
set_tests_properties(H5COPY-grp_empty-DIFF PROPERTIES  DEPENDS "H5COPY-grp_empty")
add_test(H5COPY-grp_dsets-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/grp_dsets.out.h5")
add_test(H5COPY-grp_dsets "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/grp_dsets.out.h5" "-v" "-s" "grp_dsets" "-d" "grp_dsets")
set_tests_properties(H5COPY-grp_dsets PROPERTIES  DEPENDS "H5COPY-grp_dsets-clear-objects")
add_test(H5COPY-grp_dsets-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/grp_dsets.out.h5" "grp_dsets" "grp_dsets")
set_tests_properties(H5COPY-grp_dsets-DIFF PROPERTIES  DEPENDS "H5COPY-grp_dsets")
add_test(H5COPY-grp_nested-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/grp_nested.out.h5")
add_test(H5COPY-grp_nested "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/grp_nested.out.h5" "-v" "-s" "grp_nested" "-d" "grp_nested")
set_tests_properties(H5COPY-grp_nested PROPERTIES  DEPENDS "H5COPY-grp_nested-clear-objects")
add_test(H5COPY-grp_nested-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/grp_nested.out.h5" "grp_nested" "grp_nested")
set_tests_properties(H5COPY-grp_nested-DIFF PROPERTIES  DEPENDS "H5COPY-grp_nested")
add_test(H5COPY-simple_group-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/simple_group.out.h5")
add_test(H5COPY-simple_group-prefill "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/simple_group.out.h5" "-v" "-s" "grp_dsets" "-d" "grp_dsets")
set_tests_properties(H5COPY-simple_group-prefill PROPERTIES  DEPENDS "H5COPY-simple_group-clear-objects")
add_test(H5COPY-simple_group "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/simple_group.out.h5" "-v" "-s" "/grp_dsets/simple" "-d" "/grp_dsets/simple_group")
set_tests_properties(H5COPY-simple_group PROPERTIES  DEPENDS "H5COPY-simple_group-prefill")
add_test(H5COPY-simple_group-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/simple_group.out.h5" "/grp_dsets/simple" "/grp_dsets/simple_group")
set_tests_properties(H5COPY-simple_group-DIFF PROPERTIES  DEPENDS "H5COPY-simple_group")
add_test(H5COPY-grp_rename-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/grp_rename.out.h5")
add_test(H5COPY-grp_rename "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/grp_rename.out.h5" "-v" "-s" "grp_dsets" "-d" "grp_rename")
set_tests_properties(H5COPY-grp_rename PROPERTIES  DEPENDS "H5COPY-grp_rename-clear-objects")
add_test(H5COPY-grp_rename-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/grp_rename.out.h5" "grp_dsets" "grp_rename")
set_tests_properties(H5COPY-grp_rename-DIFF PROPERTIES  DEPENDS "H5COPY-grp_rename")
add_test(H5COPY-grp_dsets_rename-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/grp_dsets_rename.out.h5")
add_test(H5COPY-grp_dsets_rename-prefill "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/grp_dsets_rename.out.h5" "-v" "-s" "grp_dsets" "-d" "grp_rename")
set_tests_properties(H5COPY-grp_dsets_rename-prefill PROPERTIES  DEPENDS "H5COPY-grp_dsets_rename-clear-objects")
add_test(H5COPY-grp_dsets_rename "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/grp_dsets_rename.out.h5" "-v" "-s" "grp_dsets" "-d" "/grp_rename/grp_dsets")
set_tests_properties(H5COPY-grp_dsets_rename PROPERTIES  DEPENDS "H5COPY-grp_dsets_rename-prefill")
add_test(H5COPY-grp_dsets_rename-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/grp_dsets_rename.out.h5" "grp_dsets" "/grp_rename/grp_dsets")
set_tests_properties(H5COPY-grp_dsets_rename-DIFF PROPERTIES  DEPENDS "H5COPY-grp_dsets_rename")
add_test(H5COPY-A_B1_simple-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/A_B1_simple.out.h5")
add_test(H5COPY-A_B1_simple "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/A_B1_simple.out.h5" "-vp" "-s" "simple" "-d" "/A/B1/simple")
set_tests_properties(H5COPY-A_B1_simple PROPERTIES  DEPENDS "H5COPY-A_B1_simple-clear-objects")
add_test(H5COPY-A_B1_simple-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/A_B1_simple.out.h5" "simple" "/A/B1/simple")
set_tests_properties(H5COPY-A_B1_simple-DIFF PROPERTIES  DEPENDS "H5COPY-A_B1_simple")
add_test(H5COPY-A_B2_simple2-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/A_B2_simple2.out.h5")
add_test(H5COPY-A_B2_simple2 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/A_B2_simple2.out.h5" "-vp" "-s" "simple" "-d" "/A/B2/simple2")
set_tests_properties(H5COPY-A_B2_simple2 PROPERTIES  DEPENDS "H5COPY-A_B2_simple2-clear-objects")
add_test(H5COPY-A_B2_simple2-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/A_B2_simple2.out.h5" "simple" "/A/B2/simple2")
set_tests_properties(H5COPY-A_B2_simple2-DIFF PROPERTIES  DEPENDS "H5COPY-A_B2_simple2")
add_test(H5COPY-C_D_simple-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/C_D_simple.out.h5")
add_test(H5COPY-C_D_simple "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/C_D_simple.out.h5" "-vp" "-s" "/grp_dsets/simple" "-d" "/C/D/simple")
set_tests_properties(H5COPY-C_D_simple PROPERTIES  DEPENDS "H5COPY-C_D_simple-clear-objects")
add_test(H5COPY-C_D_simple-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/C_D_simple.out.h5" "/grp_dsets/simple" "/C/D/simple")
set_tests_properties(H5COPY-C_D_simple-DIFF PROPERTIES  DEPENDS "H5COPY-C_D_simple")
add_test(H5COPY-E_F_grp_dsets-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/E_F_grp_dsets.out.h5")
add_test(H5COPY-E_F_grp_dsets "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/E_F_grp_dsets.out.h5" "-vp" "-s" "/grp_dsets" "-d" "/E/F/grp_dsets")
set_tests_properties(H5COPY-E_F_grp_dsets PROPERTIES  DEPENDS "H5COPY-E_F_grp_dsets-clear-objects")
add_test(H5COPY-E_F_grp_dsets-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/E_F_grp_dsets.out.h5" "/grp_dsets" "/E/F/grp_dsets")
set_tests_properties(H5COPY-E_F_grp_dsets-DIFF PROPERTIES  DEPENDS "H5COPY-E_F_grp_dsets")
add_test(H5COPY-G_H_grp_nested-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/G_H_grp_nested.out.h5")
add_test(H5COPY-G_H_grp_nested "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/G_H_grp_nested.out.h5" "-vp" "-s" "/grp_nested" "-d" "/G/H/grp_nested")
set_tests_properties(H5COPY-G_H_grp_nested PROPERTIES  DEPENDS "H5COPY-G_H_grp_nested-clear-objects")
add_test(H5COPY-G_H_grp_nested-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/h5copytst.h5" "./testfiles/G_H_grp_nested.out.h5" "/grp_nested" "/G/H/grp_nested")
set_tests_properties(H5COPY-G_H_grp_nested-DIFF PROPERTIES  DEPENDS "H5COPY-G_H_grp_nested")
add_test(H5COPY_F-region_ref-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/region_ref.out.h5")
add_test(H5COPY_F-region_ref "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-f" "ref" "-i" "./testfiles/h5copy_ref.h5" "-o" "./testfiles/region_ref.out.h5" "-v" "-s" "/" "-d" "/COPY")
set_tests_properties(H5COPY_F-region_ref PROPERTIES  DEPENDS "H5COPY_F-region_ref-clear-objects")
add_test(H5COPY-ext_link-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/ext_link.out.h5")
add_test(H5COPY-ext_link "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copy_extlinks_src.h5" "-o" "./testfiles/ext_link.out.h5" "-v" "-s" "/group_ext/extlink_dset" "-d" "/copy1_dset")
set_tests_properties(H5COPY-ext_link PROPERTIES  DEPENDS "H5COPY-ext_link-clear-objects")
add_test(H5COPY_F-ext_link_f-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/ext_link_f.out.h5")
add_test(H5COPY_F-ext_link_f "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-f" "ext" "-i" "./testfiles/h5copy_extlinks_src.h5" "-o" "./testfiles/ext_link_f.out.h5" "-v" "-s" "/group_ext/extlink_dset" "-d" "/copy2_dset")
set_tests_properties(H5COPY_F-ext_link_f PROPERTIES  DEPENDS "H5COPY_F-ext_link_f-clear-objects")
add_test(H5COPY-ext_dangle_noobj-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/ext_dangle_noobj.out.h5")
add_test(H5COPY-ext_dangle_noobj "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copy_extlinks_src.h5" "-o" "./testfiles/ext_dangle_noobj.out.h5" "-v" "-s" "/group_ext/extlink_notyet1" "-d" "/copy_dangle1_1")
set_tests_properties(H5COPY-ext_dangle_noobj PROPERTIES  DEPENDS "H5COPY-ext_dangle_noobj-clear-objects")
add_test(H5COPY_F-ext_dangle_noobj_f-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/ext_dangle_noobj_f.out.h5")
add_test(H5COPY_F-ext_dangle_noobj_f "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-f" "ext" "-i" "./testfiles/h5copy_extlinks_src.h5" "-o" "./testfiles/ext_dangle_noobj_f.out.h5" "-v" "-s" "/group_ext/extlink_notyet1" "-d" "/copy_dangle1_2")
set_tests_properties(H5COPY_F-ext_dangle_noobj_f PROPERTIES  DEPENDS "H5COPY_F-ext_dangle_noobj_f-clear-objects")
add_test(H5COPY-ext_dangle_nofile-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/ext_dangle_nofile.out.h5")
add_test(H5COPY-ext_dangle_nofile "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copy_extlinks_src.h5" "-o" "./testfiles/ext_dangle_nofile.out.h5" "-v" "-s" "/group_ext/extlink_notyet2" "-d" "/copy_dangle2_1")
set_tests_properties(H5COPY-ext_dangle_nofile PROPERTIES  DEPENDS "H5COPY-ext_dangle_nofile-clear-objects")
add_test(H5COPY_F-ext_dangle_nofile_f-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/ext_dangle_nofile_f.out.h5")
add_test(H5COPY_F-ext_dangle_nofile_f "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-f" "ext" "-i" "./testfiles/h5copy_extlinks_src.h5" "-o" "./testfiles/ext_dangle_nofile_f.out.h5" "-v" "-s" "/group_ext/extlink_notyet2" "-d" "/copy_dangle2_2")
set_tests_properties(H5COPY_F-ext_dangle_nofile_f PROPERTIES  DEPENDS "H5COPY_F-ext_dangle_nofile_f-clear-objects")
add_test(H5COPY-ext_link_group-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/ext_link_group.out.h5")
add_test(H5COPY-ext_link_group "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copy_extlinks_src.h5" "-o" "./testfiles/ext_link_group.out.h5" "-v" "-s" "/group_ext" "-d" "/copy1_group")
set_tests_properties(H5COPY-ext_link_group PROPERTIES  DEPENDS "H5COPY-ext_link_group-clear-objects")
add_test(H5COPY_F-ext_link_group_f-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/ext_link_group_f.out.h5")
add_test(H5COPY_F-ext_link_group_f "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-f" "ext" "-i" "./testfiles/h5copy_extlinks_src.h5" "-o" "./testfiles/ext_link_group_f.out.h5" "-v" "-s" "/group_ext" "-d" "/copy2_group")
set_tests_properties(H5COPY_F-ext_link_group_f PROPERTIES  DEPENDS "H5COPY_F-ext_link_group_f-clear-objects")
add_test(H5COPY-CMP-h5copy_misc1-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/h5copy_misc1.out.h5" "./testfiles/h5copy_misc1.out.out" "./testfiles/h5copy_misc1.out.out.err")
add_test(H5COPY-CMP-h5copy_misc1 "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-D" "TEST_PROGRAM=/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-D" "TEST_ARGS=-i;./testfiles/h5copytst.h5;-o;./testfiles/h5copy_misc1.out.h5;-v;-s;/simple;-d;/g1/g2/simple" "-D" "TEST_FOLDER=/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/tools/h5copy" "-D" "TEST_OUTPUT=./testfiles/h5copy_misc1.out.out" "-D" "TEST_EXPECT=1" "-D" "TEST_REFERENCE=./testfiles/h5copy_misc1.out" "-D" "TEST_MASK=true" "-P" "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/config/cmake_ext_mod/runTest.cmake")
set_tests_properties(H5COPY-CMP-h5copy_misc1 PROPERTIES  DEPENDS "H5COPY-CMP-h5copy_misc1-clear-objects")
add_test(H5COPY_SAME-samefile1-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/samefile1.out.h5")
add_test(H5COPY_SAME-samefile1-prefill "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/samefile1.out.h5" "-v" "-s" "/simple" "-d" "/simple")
set_tests_properties(H5COPY_SAME-samefile1-prefill PROPERTIES  DEPENDS "H5COPY_SAME-samefile1-clear-objects")
add_test(H5COPY_SAME-samefile1 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/samefile1.out.h5" "-o" "./testfiles/samefile1.out.h5" "-v" "-s" "/simple" "-d" "/simple_cp")
set_tests_properties(H5COPY_SAME-samefile1 PROPERTIES  DEPENDS "H5COPY_SAME-samefile1-prefill")
add_test(H5COPY_SAME-samefile1-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/samefile1.out.h5" "./testfiles/samefile1.out.h5" "/simple" "/simple_cp")
set_tests_properties(H5COPY_SAME-samefile1-DIFF PROPERTIES  DEPENDS "H5COPY_SAME-samefile1")
add_test(H5COPY_SAME-samefile2-clear-objects "/usr/local/Cellar/cmake/3.6.0_1/bin/cmake" "-E" "remove" "./testfiles/samefile2.out.h5")
add_test(H5COPY_SAME-samefile2-prefill "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/h5copytst.h5" "-o" "./testfiles/samefile2.out.h5" "-v" "-s" "/grp_dsets" "-d" "/grp_dsets")
set_tests_properties(H5COPY_SAME-samefile2-prefill PROPERTIES  DEPENDS "H5COPY_SAME-samefile2-clear-objects")
add_test(H5COPY_SAME-samefile2 "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5copy" "-i" "./testfiles/samefile2.out.h5" "-o" "./testfiles/samefile2.out.h5" "-v" "-s" "/grp_dsets" "-d" "/grp_dsets_cp")
set_tests_properties(H5COPY_SAME-samefile2 PROPERTIES  DEPENDS "H5COPY_SAME-samefile2-prefill")
add_test(H5COPY_SAME-samefile2-DIFF "/Users/tjcorona/Development/Software/Albany/Dependencies/hdf5-1.8.16/build/bin/h5diff" "-q" "./testfiles/samefile2.out.h5" "./testfiles/samefile2.out.h5" "/grp_dsets" "/grp_dsets_cp")
set_tests_properties(H5COPY_SAME-samefile2-DIFF PROPERTIES  DEPENDS "H5COPY_SAME-samefile2")
